// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct LoginData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static LoginData GetRootAsLoginData(ByteBuffer _bb) { return GetRootAsLoginData(_bb, new LoginData()); }
  public static LoginData GetRootAsLoginData(ByteBuffer _bb, LoginData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public LoginData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool IsSignin { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string Id { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(6); }
  public string Pass { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetPassBytes() { return __p.__vector_as_arraysegment(8); }
  public bool IsSuccess { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<LoginData> CreateLoginData(FlatBufferBuilder builder,
      bool isSignin = false,
      StringOffset idOffset = default(StringOffset),
      StringOffset passOffset = default(StringOffset),
      bool isSuccess = false) {
    builder.StartObject(4);
    LoginData.AddPass(builder, passOffset);
    LoginData.AddId(builder, idOffset);
    LoginData.AddIsSuccess(builder, isSuccess);
    LoginData.AddIsSignin(builder, isSignin);
    return LoginData.EndLoginData(builder);
  }

  public static void StartLoginData(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddIsSignin(FlatBufferBuilder builder, bool isSignin) { builder.AddBool(0, isSignin, false); }
  public static void AddId(FlatBufferBuilder builder, StringOffset idOffset) { builder.AddOffset(1, idOffset.Value, 0); }
  public static void AddPass(FlatBufferBuilder builder, StringOffset passOffset) { builder.AddOffset(2, passOffset.Value, 0); }
  public static void AddIsSuccess(FlatBufferBuilder builder, bool isSuccess) { builder.AddBool(3, isSuccess, false); }
  public static Offset<LoginData> EndLoginData(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<LoginData>(o);
  }
  public static void FinishLoginDataBuffer(FlatBufferBuilder builder, Offset<LoginData> offset) { builder.Finish(offset.Value); }
};

